### ISSUE TITLE
springboot2.conf uri_filter, problem with glob

### ISSUE THREAD

**Issue by ntlug** [netdata/go.d.plugin#240]
So, the following works (regexp):

    - name: log-service
        url: http://localhost:8098/actuator/prometheus
        uri_filter:
          includes:
            - ~ ^/log/.*

But if I try glob, it doesn't (I get ERROR: main[main] skipping 'springboot2': yaml: line 173: did not find expected alphabetic or numeric character):

    - name: log-service
        url: http://localhost:8098/actuator/prometheus
        uri_filter:
          includes:
            - * */log/.*

**Comment by Wing924** [comment]
@ntlug can you try this?
```yml
- name: log-service
    url: http://localhost:8098/actuator/prometheus
    uri_filter:
      includes:
        - * /log/*
```
