### ISSUE TITLE
Using header option in httpcheck

### ISSUE THREAD

**Issue by glennie** [netdata/go.d.plugin#249]
Hi,
I'd like to use 'headers' for a specific httpcheck.
My config looks like:

```yaml
jobs:
 - name: "mycheck"
   url: "https://127.0.0.1:443/page
   headers:
    Host: "www.somedomain.org"
   tls_skip_verify: yes
   response_match: "my regexp"
```

But, check doesn't override the host header. Therefore, the request is being served by the defaut vhost.
What am I doing something wrong? How to override the  ```Host:```  properly?
Many thanks,
