### ISSUE TITLE
`coredns` Filter Examples?

### ISSUE THREAD

**Issue by JasonSwindle** [netdata/go.d.plugin#267]
Howdy,

I've been trying to get the CoreDNS filters (include/exclude) to work, but I'm having a heck of a time figuring it out.  My Corefile is very simple:

```
. {
  forward . tls://1.1.1.1 tls://1.0.0.1 {
    tls_servername cloudflare-dns.com
    health_check 5s
    expire 30s
  }

  prometheus
  errors
  log
}
```

but I just cannot get it to work.  From what I understand, my zone is ".", and my servers are the two TLS IPs.   Help?

On feature request front, why not enable all zones and servers by default, and then have the end-user exclude what they don't want?

**Comment by ilyam8** [comment]
Hi @JasonSwindle 	

Syntax is

https://github.com/netdata/go.d.plugin/blob/d975e81aad7c5f2bdf96bdb83cee07b42574ce4f/config/go.d/coredns.conf#L67-L75

to match all try this

```yaml
jobs:
  - name : some_name
    url  : some_url
    per_server_stats: 
      includes: 
        - '* *'
    per_zone_stats: 
      includes: 
        - '* *'
```
