### ISSUE TITLE
vsphere go plugin uses vm_id in metrics instead of vm_name

### ISSUE THREAD

**Issue by nghtrifork** [netdata/go.d.plugin#336]
Environment:
- Netdata 1.19.0
- Ubuntu (64-bit)

I have seen this issue https://github.com/netdata/go.d.plugin/issues/274 and this PR https://github.com/netdata/netdata/pull/6966 which enable the API to show us the family. In netdata I can also see in each host / virtual machine with the name, but metrics are export with their ID, e.g. host_5, host_28, vm_1, vm_20, vm_35.

I would like to export metrics to a backend (graphite) and use them in grafana. However, that makes it a bit hard to figure out what is what since I don't know what vm_20 is unless I take a look in the netdata charts (and find it by family). In the issue @ilyam8 says 

> I didnt add vm-name to the chartID because name is not static, you can rename vm - if i add vm-name to the chartID i will have to delete all old charts and create new on rename.

wihch I understand - you can rename a VM (or a host) and then the statistics wouldn't hold up. However that's not the case with my expected usage and I prefer to lose them and get new metrics/dashboard. 

Would it be possible to change that (make it configurable) so we can choose the way metrics will be pushed to netdata (and backend)? So when we configure a job we can specify `metrics=name` or `metrics=id` where it defaults by `id`

```jobs:
  - name     : vcenter1
     url      : https://203.0.113.0
     username : admin@vsphere.local
     password : somepassword
     metrics: :name
```

**Comment by ilyam8** [comment]
Hi @nghtrifork 👋 

First of all i completely agree that lack of vm name in exported metrics is a problem.

In addition to vm name it would be nice to have host, cluster and datacenter. Probably even folders because they mean grouping.

Unfortunately there is no way to add them because of lack labels support 😔 

The only thing we can do is to add values to the chart id/dimension id.

Example:

- vm_1
- vm_1_name
- vm_1_name_host
- vm_1_name_host_cluster
- vm_1_name_host_cluster_datacenter

Or any combination of them.

It seem we need to make it configurable. Like:

```yaml
  - name     : vcenter1
     url      : https://203.0.113.0
     username : admin@vsphere.local
     password : somepassword
     vm_metrics:
       - id: yes
       - name: yes
       - host: yes
       - cluster: yes
       - datacenter: yes
```
