### ISSUE TITLE
httpcheck: allow setting custom user agent

### ISSUE THREAD

**Issue by ovv** [netdata/go.d.plugin#379]
I would like to filter the httpcheck request from my access logs, setting a custom user-agent would help me.

**Comment by ilyam8** [comment]
Hi @ovv 

There is `header` option in the config

https://github.com/netdata/go.d.plugin/blob/eb7cd315114b8d13eaa4545ae7c6009e67b57049/config/go.d/httpcheck.conf#L114-L118

```yaml
jobs:
  - name: jira
    url: https://jira.localdomain/
    headers:
      User-Agent: "myCustomUserAgent"
```
