### ISSUE TITLE
web_log  'regexp' log_type not working as expected 

### ISSUE THREAD

**Issue by rymonroe** [netdata/go.d.plugin#400]
I have a custom nginx log format with custom fields and am trying to use the web_log plugin with the below web_log.conf.
The check is successful and data starts to populate in Netdata dashboard but every request is 'unmatched'. Below is screen shot from my dashboard, am I doing anything wrong? Thanks.

![Screen Shot 2020-07-11 at 7 46 36 PM](https://user-images.githubusercontent.com/18293132/87237808-4c004280-c3af-11ea-90f9-da1f33158e39.png)

web_log.conf
```
jobs:
  - name: testnginx
    path: '/opt/nginx/access.log'
    log_type: regexp
    regexp_config:
      pattern: '\S+\s+\S+\s+\S+\s+\S+\s+(?P<request_time>\S+)\s+-\s+-\s+(?P<status>\S+)\s+\S+\s+(?P<request_length>\S+)\s+(?P<bytes_sent>\S+)\s+(?P<request>\S+\s\S+\s\S+).*$'
```

Sample log:
2020-07-11T20:25:46+00:00  www.google.com     12.23.45.67:12345     12.23.45.67:12345      0.001   -       -       200     200     144     0       GET /crazy-endpoint HTTP/1.1      custhostname-12345-123456-1      HealthChecker/2.0   12.345.67.89    hostname-12345-123456-1      12.345.67.89   -       -       -       -       -       -       green   -1      /really/long/path       /path  ab-1    starwars black   -       jedi cd-2    abc     dev   http    -

**Comment by ilyam8** [comment]
hi, can you show your log format?

**Comment by rymonroe** [comment]
> hi, can you show your log format?

2020-07-11T20:25:46+00:00 www.google.com 12.23.45.67:12345 12.23.45.67:12345 0.001 - - 200 200 144 0 GET /crazy-endpoint HTTP/1.1 custhostname-12345-123456-1 HealthChecker/2.0 12.345.67.89 hostname-12345-123456-1 12.345.67.89 - - - - - - green -1 /really/long/path /path ab-1 starwars black - jedi cd-2 abc dev http -

**Comment by ilyam8** [comment]
i saw log line, i meant log format from the nginx configuration

like

```cmd
log_format custom '"$http_referer" "$http_user_agent" '
                  '$remote_addr - $remote_user [$time_local] '
                  '"$request" $status $body_bytes_sent'
```

**Comment by rymonroe** [comment]
`'$time_iso8601\t$hostname\t$remote_addr:$remote_port\t'
                     '$upstream_addr\t$request_time\t-\t-\t'
                     '$status\t$upstream_status\t$request_length\t'
                     '$body_bytes_sent\t'
                     '$request\t$upstream_http_x_apigee_message_id\t'
                     '$http_user_agent\t$host\t$hostname-$pid-$connection-$connection_requests\t$my_nginx_var_xff\t'
                     '$upstream_http_x_apigee_fault_flag\t$upstream_http_x_apigee_fault_source\t$upstream_http_x_apigee_fault_code\t'
                     '$upstream_http_x_apigee_fault_policy\t$upstream_http_x_apigee_fault_flow\t$upstream_http_x_apigee_fault_revision\t'
                     '$upstream_http_x_apigee_dp_color\t$my_x_apigee_target_latency\t'
                     '$upstream_http_x_apigee_proxy\t$upstream_http_x_apigee_proxy_basepath\t'
                     '$self_region\t$self_pod\t$self_color\t$ssl_protocol\t$upstream_pod\t$upstream_region\t'
                     '$upstream_org\t$upstream_env\t$my_nginx_var_proto\t$upstream_http_x_apigee_nat';`

**Comment by ilyam8** [comment]
Well, something like that could do.

```yaml
- name: testnginx
  path: '/opt/nginx/access.log'
  log_type: csv
  csv_config:
    format: '- - - - $request_time - - $status - $request_length $body_bytes_sent $request_method $request_uri $server_protocol'
    delimiter: '	'  # tab
```

if it doesnt work try debug mode

> https://github.com/netdata/go.d.plugin/tree/master/modules/weblog#troubleshooting

**Comment by rymonroe** [comment]
> Well, something like that could do.
> 
> ```yaml
> - name: testnginx
>   path: '/opt/nginx/access.log'
>   log_type: csv
>   csv_config:
>     format: '- - - - $request_time - - $status - $request_length $body_bytes_sent $request_method $request_uri $server_protocol'
>     delimiter: '	'  # tab
> ```
> 
> if it doesnt work try debug mode
> 
> > https://github.com/netdata/go.d.plugin/tree/master/modules/weblog#troubleshooting

Thanks for response I tried your suggestion changing 'delimiter' to 'field_delimiter' and got the below error.

ERROR: 
check failed: parse last line: csv parse: unmatched line (2020-07-14T18:44:49+00:00     d010.....http.      -)

**Comment by ilyam8** [comment]
> changing 'delimiter' to 'field_delimiter'

Why did you do that?

I see it is `delimiter`

https://github.com/netdata/go.d.plugin/blob/b671e11db3cf554df7d9735ed7255b25052ca638/pkg/logs/csv.go#L12-L18

could you provide [weblog debug](https://github.com/netdata/go.d.plugin/tree/master/modules/weblog#troubleshooting) output?

**Comment by rymonroe** [comment]
I was getting error until I changed to field_delimiter. I'm v1.23.1 but it was upgraded from pretty old version so it's possible something went wrong.
I'll check the debug logs.

**Comment by rymonroe** [comment]
The debug output for csvconfig is below. It looks like it doesn't like my delimiter value.
The debug output for regexp is very long and just seems to state that lines are unmatched. I can post this as well if interested. 

` INFO  ] main[main] plugin.go:102 instance is started
[ INFO  ] main[main] setup.go:39 loading config file
[ INFO  ] main[main] setup.go:47 looking for 'go.d.conf' in [/opt/netdata/usr/lib/netdata/conf.d/go.d]
[ WARN  ] main[main] setup.go:51 couldn't find config, will use defaults
[ INFO  ] main[main] plugin.go:106 using config: enabled 'true', default_run 'true', max_procs '0', explicitly enabled modules '0'
[ INFO  ] main[main] setup.go:66 loading modules
[ INFO  ] main[main] setup.go:85 enabled/registered modules: 1/43
[ INFO  ] main[main] setup.go:90 building discovery config
[ INFO  ] main[main] setup.go:116 looking for 'web_log.conf' in [/opt/netdata/usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:123 found '/opt/netdata/usr/lib/netdata/conf.d/go.d/web_log.conf
[ INFO  ] main[main] setup.go:128 dummy/read/watch paths: 0/1/0
[ INFO  ] discovery[manager] manager.go:90 registered discoverers: [file discovery: [file reader]]
[ INFO  ] discovery[manager] manager.go:95 instance is started
[ INFO  ] run[manager] run.go:30 instance is started
[ INFO  ] discovery[file manager] discovery.go:71 instance is started
[ INFO  ] build[manager] build.go:91 instance is started
[ INFO  ] discovery[file reader] read.go:39 instance is started
[ INFO  ] discovery[file reader] read.go:40 instance is stopped
[ WARN  ] build[manager] build.go:200 couldn't build job: yaml: unmarshal errors:
  line 5: cannot unmarshal !!str `	` into int32`

**Comment by ilyam8** [comment]
```  
[ WARN  ] build[manager] build.go:200 couldn't build job: yaml: unmarshal errors:
  line 5: cannot unmarshal !!str `	` into int32`
```

it seems your configuration file has some syntax errors.

> /opt/netdata/usr/lib/netdata/conf.d/go.d/web_log.conf

did you modify that file? could you show the content?

**Comment by ilyam8** [comment]
ok, i see the problem `delimiter` is not a string, but rune

https://github.com/netdata/go.d.plugin/blob/b671e11db3cf554df7d9735ed7255b25052ca638/pkg/logs/csv.go#L15

try

```yaml
delimiter: 9
```

**Comment by rymonroe** [comment]
Below is the error I get when changing delimiter to 9. I also tried 1-11 with same error.

`[ DEBUG ] web_log[monroenginx] parser.go:78 log_type is csv, skipping auto-detection
[ DEBUG ] web_log[monroenginx] parser.go:81 config: {FieldsPerRecord:-1 Delimiter:9 TrimLeadingSpace:true Format:- - - - $request_time - - $status - $request_length $body_bytes_sent $request_method $request_uri $server_protocol CheckField:0xbf9d30}
[ WARN  ] web_log[monroenginx] weblog.go:103 check failed: create parser: bad csv format '- - - - $request_time - - $status - $request_length $body_bytes_sent $request_method $request_uri $server_protocol': zero fields
[ ERROR ] web_log[monroenginx] job.go:149 check failed`

**Comment by ilyam8** [comment]
> Below is the error I get when changing delimiter to 9. I also tried 1-11 with same error.

`9` is tab, it seems you need to use same delimites in the `format` option, [there](https://github.com/netdata/go.d.plugin/issues/400#issuecomment-657638792) i used spaces, should be tabs.

```yaml
- name: testnginx
  path: '/opt/nginx/access.log'
  log_type: csv
  csv_config:
    format: '-	-	-	-	$request_time	-	-	$status	-	$request_length	$body_bytes_sent	$request_method	$request_uri	$server_protocol'
    delimiter: 9
```

**Comment by rymonroe** [comment]
Got it to work with the below config which is very similar to the one above but with 'request' combined' Thanks for your help.

```
jobs:
  - name: monroenginx
    path: '/opt/apigee/var/log/edge-router/nginx/*stage.9001_access_log'
    log_type: csv
    csv_config:
      format: '-        -       -       -       $request_time   -       -       $status -       $request_length $body_bytes_sent        $request'
```
