### ISSUE TITLE
filecheck: make dir size calculation optional

### ISSUE THREAD

**Issue by ilyam8** [netdata/go.d.plugin#488]
[`filecheck`](https://github.com/netdata/go.d.plugin/tree/master/modules/filecheck#filecheck) collector should have `collect_size` option.

```yaml
jobs:
  - name: name
    dirs:
      include: [ ... ]
      collect_size: yes/no
```
