### ISSUE TITLE
prometheus: add `expected_prefix` configuration option

### ISSUE THREAD

**Issue by ilyam8** [netdata/go.d.plugin#540]
@g3offrey Hi 👋 Thx for the contribution!

> The only downside that I can see doing this is that the 8080 port could be used by another service and metrics be reported as "Traefik Local".

Yes, you are right. There is one thing we can do: [a metric name should starts with _an application prefix_](https://prometheus.io/docs/practices/naming/#metric-names).

We can add some option, for example `expected_prefix`, and if it is set we will try to find at least one metric with that prefix - no matches => the job fails to start.

Example:

```yaml
  - name: traefik_local
    url: 'http://127.0.0.1:8080/metrics'
    expected_prefix: 'traefik_'
```

_Originally posted by @ilyam8 in https://github.com/netdata/go.d.plugin/issues/539#issuecomment-762318894_
