### ISSUE TITLE
Prometheus endpoint collector multiplies raw values by 1000

### ISSUE THREAD

**Issue by Ziars** [netdata/go.d.plugin#544]
Greetings!

I'm trying to use Netdata v1.28.0 for metrics collection from [prometheus endpoints](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/prometheus). After configuring it for [redis-exporter](https://github.com/oliver006/redis_exporter) I discovered that the values ​​of the most metrics are multiplied by 1000, for example - raw `redis_up` metric:

``` console
$ curl -s "http://localhost:9121/metrics" | grep -P '^redis_up\b'
redis_up 1
```
And the same metric received from Netdata:

``` console
$ curl -s "http://myhost.net:19999/api/v1/allmetrics%3Fformat=prometheus_all_hosts&source=raw" | grep -P 'netdata_prometheus_redis_up\b'
netdata_prometheus_redis_up{chart="prometheus_redis_exporter_local.redis_up",family="redis_up",dimension="redis_up",instance="lxd-redis"} 1000 1609179403020
```

Plugin configuration was close to the default one, i.e.:

``` yaml
autodetection_retry: 300                                                                                                                                                                                     
max_time_series: 2048                                                                                                                                                                                        
priority: 70000                                                                                                                                                                                              
update_every: 10 

jobs:
  - name: redis_exporter_local
    url: 'http://127.0.0.1:9121/metrics'
```

After checking the source code I've found this constant:

- https://github.com/netdata/go.d.plugin/blob/192e776940faac85e8f742bc01e6bb9d1c6d5108/modules/prometheus/collect.go#L10

Which is used for further multiplying the values ​​of each metric type:

- https://github.com/netdata/go.d.plugin/blob/fb90e49e8388f7301c862045ea5d8a229f596caf/modules/prometheus/collect_histogram.go#L36
- https://github.com/netdata/go.d.plugin/blob/fb90e49e8388f7301c862045ea5d8a229f596caf/modules/prometheus/collect_gauge_counter.go#L27
- https://github.com/netdata/go.d.plugin/blob/fb90e49e8388f7301c862045ea5d8a229f596caf/modules/prometheus/collect_summary.go#L35

What is the purpose of this multiplication? Is there a way to disable it somehow? Such multiplication makes it inconvenient to use Netdata as a metric collector from Prometheus exporters (impossible to get raw metrics from them). Thank you in advance!
