### ISSUE TITLE
Abnormal CPU and RAM usage by go.d.plugin

### ISSUE THREAD

**Issue by Ziars** [netdata/go.d.plugin#549]
Greetings!

I'm trying to use Netdata v1.28.0 for metrics collection from [prometheus endpoints](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/prometheus). After configuring it for [redis-exporter](https://github.com/oliver006/redis_exporter) I discovered the abnormal CPU and RAM consumption by go.d.plugin as seen on graphs below:

![20210202-201858](https://user-images.githubusercontent.com/24412217/106638032-73f60400-6594-11eb-87a1-91247c0e91ea.png)

1. prometheus endpoints plugin was enabled somewhere here
2. OOMkiller triggered here
3. Consumption keeps growing after restart

Memory and swap usage, same interval:

![20210113-113041](https://user-images.githubusercontent.com/24412217/106638021-72c4d700-6594-11eb-8f0a-c9db038a38c3.png)
![20210113-113058](https://user-images.githubusercontent.com/24412217/106638030-735d6d80-6594-11eb-8548-e6798ea7f4ac.png)

Plugin configuration was close to the default one, with over 500 default jobs, i.e.:

``` yaml
autodetection_retry: 300
max_time_series: 2048
priority: 70000
update_every: 10

jobs:
  - name: node_exporter_local
    url: 'http://127.0.0.1:9100/metrics'
  - name: haproxy_exporter_local
    url: 'http://127.0.0.1:9101/metrics'
  - name: statsd_exporter_local
    url: 'http://127.0.0.1:9102/metrics'
...
```

Please, check the possible reasons and let me know if any more info is needed. Thank you in advance!
