### ISSUE TITLE
Quenstion about filecheck

### ISSUE THREAD

**Issue by Tommuh** [netdata/go.d.plugin#633]
1. Is it possible to count all files in the underlying folders? Now I have to define each path where files can be found?
2. Is it possible to disable the "file existince" chart? I just want a total number from all folders. Same for "file time since last ..." and "file size".

**Comment by ilyam8** [comment]
Hi, @Tommuh. Sorry for the delayed answer. No to both points, but we can implement this if there is a request.

**Comment by ilyam8** [comment]
Let's discuss it here and I'll open new issues.

[Filecheck collects](https://github.com/netdata/go.d.plugin/tree/master/modules/filecheck#filecheck):
 - file metrics:
   - existence
   - time since the last modification
   - size
 - directory metrics:
   - existence
   - time since the last modification
   - size
   - number of files

> Is it possible to disable the "file existince" chart? I just want a total number from all folders. Same for "file time since last ..." and "file size".

I guess you mean directory metrics, not file (because you want to exclude all the file metrics)?

So something we can add `collect_dir_*: yes/no` option for every job, e.g.:

```YAML
 - name: dirs_example
   dirs:
     collect_dir_existence: no
     collect_dir_time_since_modification: no
     collect_dir_size: no
     collect_dir_num_of_files: yes
     include:
       - '/path/to/dir1'
       - '/path/to/dir2'
```

What do you think?
