### ISSUE TITLE
mongodb replica set stats not working

### ISSUE THREAD

**Issue by bompus** [netdata/go.d.plugin#634]
I'm running MongoDB 5.1.0 and I'm not seeing the go.d mongodb collector pulling replication stats in either the dashboard or when running `./go.d.plugin -d -m mongodb`

I've tested that I can run `db.serverStatus().repl` in the mongosh cli shell using the same mongodb user, which has the following permissions when I run `use admin` and `db.getUser('monitor')` in mongosh:
```
user: 'monitor',
db: 'admin',
roles: [
  { role: 'clusterMonitor', db: 'admin' },
  { role: 'read', db: 'local' },
  { role: 'read', db: 'admin' }
]
```

I'm using this config in `go.d/mongodb.conf`:
```
jobs:
  - name: local
    uri: 'mongodb://monitor:xxxxx@127.0.0.1:27017/?authSource=admin'
    timeout: 20
```

Based on release notes and research, this was implemented in #604 and should be included in the latest version.

I'm running:
`netdata v1.32.0-1-nightly`
`go.d.plugin, version: v0.31.0`
