### ISSUE TITLE
Feature Request: Share common SNMP configuration

### ISSUE THREAD

**Issue by nikobearrr** [netdata/go.d.plugin#685]
I would like to be able to share the same configuration across multiple devices.

Use case:
- I have 3 of the same switches.
- I would like to re-use the configuration posted here: https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/snmp#example-using-snmpv12 for all 3 of them without having to copy/paste it

**Comment by Ferroin** [comment]
The config files all use YAML, and the parser properly supports anchors and aliases, so it should be able to do this type of thing without needing any changes.

If you’ve never used YAML anchors or aliases before, I recommend https://blog.daemonl.com/2016/02/yaml.html as a quick primer. Generically, they let you reuse part of a YAML document elsewhere in the same document by just creating a reference ( a bit like a symlink) instead of having to manually copy all of it (and can do neat things like reusing most of a mapping but overriding specific keys).

---

@ilyam8 We might want to consider actually formally documenting that we support anchors/aliases/extend syntax, and providing some examples of how to use it. SNMP config is a trivial example of somewhere that it’s super useful, but I bet there are other places that users would be able to benefit.

**Comment by ilyam8** [comment]
Awesome idea, @Ferroin. I tested the following and it works (basically is copying `charts:` section from an job to another):

```YAML
jobs:
  - name: switch
    update_every: 10
    hostname: "192.0.2.1"
    community: public
    options:
      version: 2
    charts: &anchor
      - id: "bandwidth_port1"
        title: "Switch Bandwidth for port 1"
        units: "kilobits/s"
        type: "area"
        family: "ports"
        dimensions:
          - name: "in"
            oid: "1.3.6.1.2.1.2.2.1.10.1"
            algorithm: "incremental"
            multiplier: 8
            divisor: 1000
          - name: "out"
            oid: "1.3.6.1.2.1.2.2.1.16.1"
            multiplier: -8
            divisor: 1000
      - id: "bandwidth_port2"
        title: "Switch Bandwidth for port 2"
        units: "kilobits/s"
        type: "area"
        family: "ports"
        dimensions:
          - name: "in"
            oid: "1.3.6.1.2.1.2.2.1.10.2"
            algorithm: "incremental"
            multiplier: 8
            divisor: 1000
          - name: "out"
            oid: "1.3.6.1.2.1.2.2.1.16.2"
            multiplier: -8
            divisor: 1000
  - name: switch2
    update_every: 10
    hostname: "192.0.2.2"
    community: public
    options:
      version: 2
    charts: *anchor
```
